name: Update Milestones on README

on:
  schedule:
    - cron: "0 */6 * * *"  # Executa a cada 6 horas
  workflow_dispatch:  # Permite executar manualmente o workflow

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Fetch Milestones Data
        env:
          REPO_NAME: "projeto-crud"
          ORG_NAME: "Projeto-Fundamentos"
        run: |
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               "https://api.github.com/repos/$ORG_NAME/$REPO_NAME/milestones" \
               -o milestones.json

          MILESTONE_DATA=$(jq -r '.[] | "* [" + .title + "](" + .html_url + ") - " + (.closed_issues | tostring) + "/" + (.open_issues + .closed_issues | tostring) + " issues closed"' milestones.json)

          # Criar um novo README se não existir
          if [ ! -f profile/README.md ]; then
            echo -e "# Projeto Fundamentos - CESAR School\n\n## Milestones\n\n$MILESTONE_DATA\n" > profile/README.md
          else
            # Se o README existir, adicionar a seção de milestones
            echo -e "\n## Milestones\n\n$MILESTONE_DATA\n" >> profile/README.md
          fi
          
      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add profile/README.md
          git commit -m "Update milestones progress in README"
          git push
