name: Update Milestones on README

on:
  schedule:
    - cron: "0 */6 * * *"  # Executa a cada 6 horas
  workflow_dispatch: # Permite executar manualmente o workflow

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Fetch Milestones Data
        env:
          REPO_NAME: "projeto-crud"
          ORG_NAME: "Projeto-Fundamentos"
        run: |
          # Fetch the milestone data from the GitHub API
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               "https://api.github.com/repos/$ORG_NAME/$REPO_NAME/milestones" \
               -o milestones.json

          # Format the milestone data
          MILESTONE_DATA=$(jq -r '.[] | "* [" + .title + "](" + .html_url + ") - " + (.closed_issues | tostring) + "/" + (.open_issues + .closed_issues | tostring) + " issues closed"' milestones.json)

          # Check if the "## Milestones" section already exists
          if grep -q "## Milestones" README.md; then
              # Remove the existing section
              sed -i '/## Milestones/,/^$/d' README.md
          fi
          
          # Insert the new Milestones section after "## Visão Geral"
          sed -i "/## Visão Geral/a\\
          ## Milestones\\
          \\n$MILESTONE_DATA\\
          " README.md

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git commit -m "Update milestones progress in README"
          git push
